### ISSUE TITLE
Elasticsearch

### ISSUE THREAD

**Issue by Killian1B** [PremierLangage/platon-server#16]
# Elasticsearch

## Description

Elasticsearch is a tool for storing files in a database.  
Files can be retrieved by words or sentences present in their content.  
Elasticsearch runs in his own container (platon-elasticsearch), on the host 172.17.0.1 and the port 9200.

### Settings

Add this variable in `settings.py` to configure the host and the port of Elasticsearch.
```py
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': host,
        'port': port
    },
}
```
`host` and `port` must be identical to the host and the port of the docker container.  
Add `django_elasticsearch_dsl` in `INSTALLED_APPS` list of `settings.py`.

---
### Index data

Create a subclass of `django_elasticsearch_dsl.Document` in a `documents.py` file, to join your Model to Elasticsearch.  
Create `Index` class and `Django` class into this subclass.

#### Example

For example, a Model MyModel to index, link by Foreign and ManyToMany key at OtherModel1 and OtherModel2.

```py
class MyModel(models.Model):
    field1 = models.CharField(max_length=50)
    field2 = models.CharField(max_length=50)
    field3 = models.IntegerField()
    field4 = models.ForeignKey(OtherModel1, on_delete=CASCADE)

class OtherModel1(models.Model):
    standardField1 = models.CharField(max_length=50)
    standardField2 = models.CharField(max_length=50)
    
class OtherModel2(models.Model):
    manyToManyField = models.ManyToManyField(MyModel)
```
Here `MyModel` have 3 standard fields and 1 ForeignKey field (with `OtherModel1`).
`OtherModel1` have 2 standard fields.  
`OtherModel2` have 1 ManyToMany field (with `MyModel`).

To store in **Elasticsearch** these following fields : `field1`, `field3` and `field4`, use this class.
```py
@registry.register_document
class MyModelDocument(Document):
    class Index:
        name = "my_index_name"
        settings = {"number_of_shards": 1, "number_of_replicas": 0}

    class Django:
        model = MyModel
        fields = ["field1", "field3"]
        related_models = [OtherModel1]
    
    field4 = fields.ObjectField(properties={
        'standardField1': fields.TextField(),
    })

    def get_instances_from_related(self, related_instance):
        if isinstance(related_instance, OtherModel1):
            return related_instance.mymodel_set.all()
        elif isinstance(related_instance, OtherModel2):
            return related_instance.manyToManyField.all()
```

**MyModelDocument** :
* `field4` : Store the field `standardField1` of `field4`.
    Foreign and ManyToMany key fields cannot be in `Django` class.  
    They must be initialized in `MyModelDocument` with a `ObjectField` (to store one instance) or a `NestedField` (to store a list of instances).
* `get_instances_from_related`: Use to retrieve an instance of MyModel according to Foreign or ManyToMany field.

**Index** :  
* `name` : The name of the index in the Elasticsearch database.
* `settings` : The number of shard and replica of the index.

**Django** :  
* `model` : The Model to index.
* `fields` : Standard fields of MyModel to index.
* `related_models` : Model of Foreign or ManyToMany key fields to index.

For each subclass of `Document` created or modified, you must execute the command `./manage.py search_index --rebuild`.

Each instances of the indexed Model created or modified will be updated in Elasticsearch database.

---

### Transform indexed fields

Fields can be transformed before being indexed. There are two methods of tranformation :
* Change of type.
* Prepare field.

### Example : Change type

For example, to index `MyModel.field3` as a String rather than an Integer, the following method can be used :

Add a method to transform a field into the current Model (here `MyModel`).

```py
def int_to_string(self):
    return str(self.field3)
```

Extract the field to transform from the `Django` class.
```py
class Django:
    model = myModel
    fields = ["field1"]
    related_models = [OtherModel1]

field3 = fields.TextField(attr="int_to_string")
field4 = fields.ObjectField(properties={
    'standardField1': fields.TextField(),
})
```

### Example : Prepare field

For example, to double the value of `MyModel.field3` when it is indexed, the following method can be used :

In `MyModelDocument` add a prepare method, and extract the prepared field from the `Django` class.

```py
class Django:
    model = myModel
    fields = ["field1"]
    related_models = [OtherModel1]

field3 = fields.IntegerField()

def prepare_field3(self, instance):
    return instance.field3*2
```

---

### Queries

Queries can be created with the shortcut `Q` of `elasticsearch_dsl`. There are three types of queries :
* `match` : Do a research on one field of an index.
* `multi_match` : Do a research on some fields of an index.
* `bool` : Do a filter query on an index.

These queries can be prepared with the method `.search().query()` of the `Document` class.  
Then, data caught by the query can be retrieved with `execute()` method, or deleted with `delete()` method.

### Example

```py
# Search data where field1 is equal to "value"
query = Q("match", field1="value")

# Search data where field1 or field4.standardField1 is equal to "value"
query = Q("multi_match", query="value", fields=["field1", "field4__standardField1"])

# Search data where field1 is equal to "value" and field3 is equal to num
query = Q("bool", must=[Q("match", field1="value"), Q("match", field3=num)])
query = Q("match", field1="value") & Q("match", field3=num)

# Search data where field1 is equal to "value" or field3 is equal to num
query = Q("bool", should=[Q("match", field1="value"), Q("match", field3=num)]
query = Q("match", field1="value") | Q("match", field3=num)

# Search data where field1 is different to "value" and field3 is different from num
query = Q("bool", must_not=[Q("match", field1="value"), Q("match", field3=num)])

# Negation of a query
query = ~Q(...)

# Retrieve data
result = MyModelDocument.search().query(query).execute()

# Delete data
result = MyModelDocument.search().query(query).delete()

# Map result to queryset
result = MyModelDocument.search().query(query).to_queryset()

# Map result to a dict
# Except for to_queryset()
result.to_dict()
```
### Return

When the return value of methods `execute` and `delete` are map to a dict,  
details like request time (`took`) or timeout (`timed_out`) are present.  
But there is some differents fields :

* `execute` : 
	* `_shards` : informations on this index
	* `hits` : contain the number of data retrieve, and all these data
	
* `delete` :
	* `total` : number of data match
	* `deleted` : number of data deleted

**Comment by nimdanor** [comment]
Ok cool.
What's the type of 
```MyModelDocument.search().query(query).execute()``` ? 
 queryset ?

**Comment by Killian1B** [comment]
It's a `elasticsearch_dsl.response.Response`.  
But we can have a queryset with `MyModelDocument.search().query(query).to_queryset()`

**Comment by mciissee** [comment]
ES can be used together with DRF using this lib which is already integrated in the docker install 
https://www.merixstudio.com/blog/elasticsearch-django-rest-framework/

This lib comes with useful features like suggestions, permissions... which are not integrated on django dsl
